### ISSUE TITLE
Can't connect to freenode.

### ISSUE THREAD

**Issue by tutuca** [mneri/rice#1]
Hi! I've installed Rice in my Moto E recently.

The app looks great overall but can't connect to freenode using irc.freenode.net:6667 as usual. Neither with SSL or without.

How can I give you further information?

**Comment by mneri** [comment]
Hi tutuca.
This sounds new to me. Rice IRC Client was mainly tested on Freenode and should give no problems. I'm currently developing a new version of Rice so I don't have the old code under my hands now. I will take a look starting by the end of next week.

The code you find here is a complete rewriting of the engine Rice IRC Client is based on, not the complete client. For questions about Rice IRC Client and not about this library please, contact me via email. You can find my email on my profile page here on GitHub.

**Comment by tutuca** [comment]
Oh, ok! Sorry for the annoyance!

The client actually looks great. I'm looking forward to your new release. Cheers and thanks for the great work!

**Comment by mneri** [comment]
It's not a problem at all!
I'm glad you enjoy Rice IRC Client.
